### PR TITLE
Feature#33 fix log test

### LINKED ISSUE #33: Fix log test
# REQUIREMENTS

Fix broken logs test after employee validations introduction.
 
# DESIGN

N/A

# Acceptance Criteria
List all required acceptance criteria
- [x] Test should pass log model.

### PR DESCRIPTION
**Pull request by anxhe**
# Description

Fix broken test due a new  validations, now employees can't be created with empty arguments (name, email...). It has been a solution using the factories that were already created.

 # Testing

- Run rspec spec/models/log_spec.rb

  ## Screenshots 

Screen Recording 2021-05-04 at 11 23 09 a m

### CODE REVIEW

**Review by RobertVel666 — DISMISSED** [review]
great fix, it seems ok now keep up the great work.

**Review by RobertVel666 — DISMISSED** [review]
Well done good fixes all around.

**Review by RobertVel666 — APPROVED** [review]
Yep code nice!

**Review by Arkamis — APPROVED** [review]
LGTM!! 👍

**Pull request merged**
